// Mocks generated by Mockito 5.0.10 from annotations
// in nu_challenge/test/features/customer/presentation/customer_store_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nu_challenge/core/errors/failures.dart' as _i6;
import 'package:nu_challenge/core/usecases/usecase.dart' as _i8;
import 'package:nu_challenge/features/customer/domain/entities/customer.dart'
    as _i7;
import 'package:nu_challenge/features/customer/domain/repositories/customer_repository.dart'
    as _i2;
import 'package:nu_challenge/features/customer/domain/usecases/get_customer_usecase.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeCustomerRepository extends _i1.Fake
    implements _i2.CustomerRepository {}

class _FakeEither<L, R> extends _i1.Fake implements _i3.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetCustomerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCustomerUseCase extends _i1.Mock
    implements _i4.GetCustomerUseCase {
  MockGetCustomerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CustomerRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeCustomerRepository()) as _i2.CustomerRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Customer>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, _i7.Customer>>.value(
                  _FakeEither<_i6.Failure, _i7.Customer>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Customer>>);
}
