// Mocks generated by Mockito 5.0.10 from annotations
// in nu_challenge/test/features/product/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nu_challenge/modules/products/data/models/product_model.dart'
    as _i4;

import '../../../../mocks/datasources_mocks.dart' as _i2;
import '../../../../mocks/platform_mocks.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ProductRemoteDatasourceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDatasourceTest extends _i1.Mock
    implements _i2.ProductRemoteDatasourceTest {
  MockProductRemoteDatasourceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductModel>?> getProducts() =>
      (super.noSuchMethod(Invocation.method(#getProducts, []),
              returnValue: Future<List<_i4.ProductModel>?>.value())
          as _i3.Future<List<_i4.ProductModel>?>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkUtilsTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkUtilsTest extends _i1.Mock implements _i5.NetworkUtilsTest {
  MockNetworkUtilsTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get hasInternetAccess =>
      (super.noSuchMethod(Invocation.getter(#hasInternetAccess),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  String toString() => super.toString();
}
