// Mocks generated by Mockito 5.0.10 from annotations
// in nu_challenge/test/features/product/presentation/ui/widgets/product_card_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:nu_challenge/core/platform/currency_formats.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [CurrencyFormats].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyFormats extends _i1.Mock implements _i2.CurrencyFormats {
  MockCurrencyFormats() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String formatCurrency(double? amount) =>
      (super.noSuchMethod(Invocation.method(#formatCurrency, [amount]),
          returnValue: '') as String);
}
